import { createFileRoute, Outlet } from "@tanstack/react-router";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { Toaster } from "@/components/ui/sonner";

export const Route = createFileRoute("/_app")({
  component: AppLayout,
});

function AppLayout() {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full bg-background">
        <AppSidebar />
        <div className="flex flex-1 flex-col">
          <header className="sticky top-0 z-10 flex h-14 items-center gap-3 border-b border-border bg-background/80 px-4 backdrop-blur">
            <SidebarTrigger />
            <div className="flex-1" />
            <div className="text-xs text-muted-foreground hidden sm:block">
              Powered by Lovable AI
            </div>
          </header>
          <main className="flex-1 p-4 sm:p-6 lg:p-8">
            <Outlet />
          </main>
          <footer className="border-t border-border bg-muted/30 px-6 py-3 text-xs text-muted-foreground">
            <strong>Responsible AI:</strong> Outputs are generated by AI and may be inaccurate.
            Always review and edit before sharing. Do not submit confidential or sensitive
            personal data.
          </footer>
        </div>
      </div>
      <Toaster />
    </SidebarProvider>
  );
}